name: dask-env4
channels:
  - defaults
  - conda-forge
channel_priority: strict
dependencies:
  - python=3.10.6
  - dask[complete]=2022.10.0
  - distributed=2022.10.0
  - cloudpickle=2.2.0
  - lz4=4.0.0
  - msgpack-python=1.0.4
  - toolz=0.12.0
  - tornado
  - pyarrow
  - PyPDF2
  - pdfplumber=0.11.5
  - pycryptodome
  - requests
  - pandas=1.5.0
  - pip
  - pip:
      - s3fs==2024.5.0
      - upstash-ratelimit
      - upstash-redis
      - dnspython
      - memory-profiler
      - pytesseract
      - backoff
      - dnspython
      - opencv-python
      - pdf2image==1.17.0
      - cloudwatch
      - langchain==0.2.17
      - langchain-aws==0.1.4
      - langchain-openai==0.1.20
      - numpy
      - pymongo
      - openai==1.37.1
      - prefect==3.4.6
      - griffe
      - prefect[dask]  # Install preprocessing[dask] using pip
      - aioboto3==12.4.0
      - aiobotocore==2.12.3
      - boto3==1.34.69
      - httpx==0.27.2
      - aioitertools
      - tqdm
      - python-dotenv
      - natsort

